# base config for robot
max_robo_iterations: 50
model_class_name: DUNet2D
model_init_kwargs: {in_channels: 1, out_channels: 1}
training: {
    training_shape: [1, 256, 256],
    batch_size: 8,
    loss_criterion_config: {"method": "MSELoss"},
    optimizer_config: {"method": "Adam"},
    num_iterations_done: 5,
}
validation: {}
dry_run: {"skip": False, "shrinkage": [0, 0, 0]}

model_dir: {
    path_to_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/CREMI_DUNet_pretrained_new.zip",
    path_in_folder_to_model: "CREMI_DUNet_pretrained_new/model.py",
    path_in_folder_to_state: "CREMI_DUNet_pretrained_new/state.nn",
}

data_dir: {
    raw_data_base_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_train_raw.h5",
    path_to_raw_data: "raw",
    labelled_data_base_folder: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_train_label.h5", 
    path_to_labelled: "labelled",
    validation_raw_base: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_validation_raw.h5",
    validation_raw: "raw",
    validation_label_base: "/home/psharma/psharma/repos/tiktorch/tests/data/Fluo_N2DH_validation_label.h5",
    validation_label: "labelled"
}

class_dict: {
    1: "background",
    2: "cell"
}

